pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                // sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                // sh 'npm run test'
                echo "Test"

            }
        }
        stage('Build Image') {
            steps {
                
                    sh 'docker build -t APPCICD/.'
            
          
            }
        }
        stage ('Deploy') {
            steps {
                echo "Not Yet"
            }
        }
    }
}
